import Link from "next/link";
import { FlaskConical } from "lucide-react";

import { PageHeader } from "@/components/shared/page-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { listResearchPacketsWithPlatform } from "@/server/polibrawl/repositories/research-packet.repository";

export const metadata = {
  title: "Research Packets — PoliBrawl Admin",
  description: "AI-ready research packets generated by the keyword scanner for editorial review.",
};

const CATEGORY_COLORS: Record<string, string> = {
  money: "bg-amber-100 text-amber-900",
  account: "bg-rose-100 text-rose-900",
  kyc: "bg-sky-100 text-sky-900",
  payout: "bg-indigo-100 text-indigo-900",
  appeal: "bg-orange-100 text-orange-900",
  data_saas: "bg-emerald-100 text-emerald-900",
  api: "bg-violet-100 text-violet-900",
  legal: "bg-zinc-100 text-zinc-900",
};

export default async function ResearchPacketsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const filterCategory =
    typeof params.category === "string" ? params.category : undefined;
  const filterStatus =
    typeof params.status === "string" ? params.status : undefined;

  const packets = await listResearchPacketsWithPlatform(
    {
      ...(filterCategory ? { category: filterCategory } : {}),
      ...(filterStatus ? { status: filterStatus as "draft" | "ready" | "archived" } : {}),
    },
    { limit: 100 },
  ).catch(() => []);

  const draftCount = packets.filter((p) => p.status === "draft").length;
  const readyCount = packets.filter((p) => p.status === "ready").length;

  const categories = [
    "money", "account", "kyc", "payout", "appeal", "data_saas", "api", "legal",
  ];

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Sprint 8"
        title="Research Packets"
        description="Scanner-generated evidence bundles for editorial review. Each packet maps to one candidate and is exportable as Markdown for AI-assisted editing."
      />

      {/* Metrics */}
      <section className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Packets</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <FlaskConical className="h-5 w-5 text-muted-foreground" />
              <span className="text-3xl font-bold">{packets.length}</span>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Draft</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-zinc-700">{draftCount}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Ready for AI</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-emerald-700">{readyCount}</div>
          </CardContent>
        </Card>
      </section>

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        <Link
          href="/admin/research-packets"
          className="rounded-md border px-3 py-1 text-sm hover:bg-muted"
        >
          All
        </Link>
        {categories.map((cat) => (
          <Link
            key={cat}
            href={`/admin/research-packets?category=${cat}`}
            className={`rounded-md px-3 py-1 text-sm font-medium ${
              filterCategory === cat
                ? (CATEGORY_COLORS[cat] ?? "bg-zinc-100")
                : "border hover:bg-muted"
            }`}
          >
            {cat}
          </Link>
        ))}
        {["draft", "ready", "archived"].map((s) => (
          <Link
            key={s}
            href={`/admin/research-packets?status=${s}`}
            className={`rounded-md border px-3 py-1 text-sm ${
              filterStatus === s ? "bg-zinc-200 font-medium" : "hover:bg-muted"
            }`}
          >
            {s}
          </Link>
        ))}
      </div>

      {/* Table */}
      {packets.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center text-muted-foreground">
            <FlaskConical className="mx-auto mb-4 h-10 w-10 opacity-30" />
            <p className="text-sm">No research packets found.</p>
            <p className="mt-1 text-xs">Run the keyword scanner on a source snapshot to generate packets.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="rounded-lg border overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-muted/50 text-muted-foreground">
              <tr>
                <th className="px-4 py-3 text-left font-medium">Platform</th>
                <th className="px-4 py-3 text-left font-medium">Category</th>
                <th className="px-4 py-3 text-left font-medium">Title</th>
                <th className="px-4 py-3 text-left font-medium">Confidence</th>
                <th className="px-4 py-3 text-left font-medium">Noise</th>
                <th className="px-4 py-3 text-left font-medium">Candidate</th>
                <th className="px-4 py-3 text-left font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {packets.map((packet) => (
                <tr key={packet.id} className="hover:bg-muted/30 transition-colors">
                  <td className="px-4 py-3 font-medium">
                    <Link
                      href={`/admin/research-packets/${packet.id}`}
                      className="hover:underline"
                    >
                      {packet.platform_name}
                    </Link>
                  </td>
                  <td className="px-4 py-3">
                    <Badge
                      className={`text-xs ${CATEGORY_COLORS[packet.category] ?? "bg-zinc-100 text-zinc-900"}`}
                    >
                      {packet.category}
                    </Badge>
                  </td>
                  <td className="px-4 py-3 max-w-xs truncate text-muted-foreground">
                    <Link
                      href={`/admin/research-packets/${packet.id}`}
                      className="hover:underline hover:text-foreground"
                    >
                      {packet.title}
                    </Link>
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`font-mono text-xs font-bold ${
                        packet.confidence_score >= 60
                          ? "text-emerald-700"
                          : packet.confidence_score >= 30
                            ? "text-amber-700"
                            : "text-rose-700"
                      }`}
                    >
                      {packet.confidence_score}
                    </span>
                    <span className="text-muted-foreground text-xs">/100</span>
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`font-mono text-xs ${
                        packet.noise_score >= 40
                          ? "text-rose-700 font-bold"
                          : packet.noise_score >= 20
                            ? "text-amber-700"
                            : "text-muted-foreground"
                      }`}
                    >
                      {packet.noise_score}
                    </span>
                  </td>
                  <td className="px-4 py-3 max-w-[200px] truncate text-muted-foreground text-xs">
                    <Link
                      href={`/admin/candidates/${packet.candidate_id}`}
                      className="hover:underline hover:text-foreground"
                    >
                      {packet.candidate_headline}
                    </Link>
                  </td>
                  <td className="px-4 py-3">
                    <StatusBadge value={packet.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
