import Link from "next/link";

import { PageHeader } from "@/components/shared/page-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { listSignalCandidates } from "@/server/repositories/signal-repository";

export default async function SignalCandidatesPage() {
  const candidates = await listSignalCandidates({ status: "pending" }).catch(() => []);

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Epic 6"
        title="Signal candidate queue"
        description="Review all pending clause matches generated by the rule engine."
      />
      <div className="grid gap-4">
        {candidates.map((candidate) => (
          <Card key={candidate.id}>
            <CardHeader className="pb-3">
              <div className="flex items-start justify-between gap-4">
                <div className="space-y-1">
                  <CardTitle className="text-lg">
                    <Link href={`/admin/review/signals/${candidate.id}`} className="hover:underline">
                      {candidate.suggested_signal}
                    </Link>
                  </CardTitle>
                  <p className="text-sm text-muted-foreground">
                    {candidate.platforms?.name ?? "Platform"} ·{" "}
                    {candidate.suggested_category.replaceAll("_", " ")}
                  </p>
                </div>
                <StatusBadge value={candidate.status} />
              </div>
            </CardHeader>
            <CardContent className="space-y-2 text-sm text-muted-foreground">
              <p>{candidate.clauses?.clause_text?.slice(0, 220) ?? "No clause text"}</p>
              <p>
                Confidence: {candidate.confidence ?? "-"} · Matches:{" "}
                {Array.isArray(candidate.matched_terms)
                  ? candidate.matched_terms.join(", ")
                  : "None"}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
