// Red‑Flag Keyword Taxonomy (deterministic, easy to edit)
export const RED_FLAG_KEYWORD_TAXONOMY: Record<string, string[]> = {
  money: [
    "hold",
    "reserve",
    "withhold",
    "delay payment",
    "delay payout",
    "available balance",
    "negative balance",
    "chargeback",
    "refund",
    "withdrawal",
    "payout",
    "release funds",
  ],
  account: [
    "limit account",
    "limitation",
    "suspend",
    "terminate",
    "close account",
    "restrict access",
    "disable",
    "freeze",
    "review account",
  ],
  kyc: [
    "identity",
    "verify",
    "verification",
    "document",
    "additional information",
    "compliance review",
    "proof of identity",
    "business information",
  ],
  payout: [
    "payout",
    "withdraw",
    "settlement",
    "transfer",
    "bank account",
    "payment method",
    "recipient",
    "payment review",
  ],
  appeal: [
    "appeal",
    "dispute",
    "complaint",
    "review decision",
    "reconsider",
    "support",
    "resolution",
  ],
  data_saas: [
    "retain",
    "delete",
    "export",
    "backup",
    "access data",
    "termination",
    "ownership",
    "license",
    "customer data",
  ],
  api: [
    "API access",
    "rate limit",
    "quota",
    "suspend API",
    "developer terms",
    "usage limit",
    "deprecation",
    "service restriction",
  ],
  legal: [
    "binding arbitration",
    "class action waiver",
    "sole discretion",
    "without notice",
    "liability",
    "indemnify",
    "jurisdiction",
  ],
};

export const RED_FLAG_SUGGESTED_TITLES: Record<string, string> = {
  money: "Potential Money Control Red Flag",
  account: "Potential Account Control Red Flag",
  kyc: "Potential Verification Red Flag",
  payout: "Potential Payout Red Flag",
  appeal: "Potential Appeal Clarity Red Flag",
  data_saas: "Potential Data or SaaS Continuity Red Flag",
  api: "Potential API Access Red Flag",
  legal: "Potential Legal Terms Red Flag",
};

export const RED_FLAG_SUGGESTED_LEVELS: Record<string, string> = {
  money: "medium",
  account: "medium",
  kyc: "medium",
  payout: "medium",
  appeal: "medium",
  data_saas: "medium",
  api: "medium",
  legal: "unknown",
};
